### ISSUE TITLE
printImageStatistic to link to the gallerific image instead of the regular image page

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1016] opened 2019-07-30 20:49 UTC
Hi Stephen,

Is there a way that once you have activated Galleriffic gallery in ZPArdoise that the printImageStatistic images link to the image in the Galleriffic gallery? Now they go to the regular image page. The reason for this is that with Gallerific activated and colorbox activated the regular image page is hardly used. It would make more sense and is more consistent in my opinion.

**Comment by sbillard** [comment] 2019-07-31 00:37
You would have to make your own version of the pirntImageStatistic() 
function and use it instead.

If you copy the one in image_album_statistics you will find code that 
reads:

if ($showtitle) {
             echo '<h3><a href="' . html_encode($image->getLink()) . '" 
title="' . html_encode($image->getTitle()) . "\">\n";
             echo $image->getTitle() . "</a></h3>\n";
         }

You would change the $image->getLink() to $image->$album->getlink()

On a side note, this code seems strange to me. Apparently you only get 
the link if the $showtitle variable is set to true. You should also note 
that zpArdoise has its on version of the function. I did not try to see 
what changes were made, and maybe the copy is not even needed now. But 
maybe that is convenient for you, you can change the version in your 
customized theme and not need to make a new function.


-Stephen

**Comment by Elinth** [comment] 2019-07-31 08:26
That gave me loads of errors.  I did see as you mentioned that ZPArdoise has its own function for this. 
Would you be so kind to help me change this? 

/*` zpArdoise_printImageStatistic
  /*	- use improvements of zenphoto 1.4.6 on printRandomImages
  /*	- use improvements of zenphoto 1.4.2 on printImageStatistic (http://www.zenphoto.org/trac/ticket/1914)
  /*	- implements call of colorbox (http://www.zenphoto.org/trac/ticket/1908 and http://www.zenphoto.org/trac/ticket/1909)
 */

function zpArdoise_printImageStatistic($number, $option, $albumfolder = '', $showtitle = false, $showdate = false, $showdesc = false, $desclength = 40, $showstatistic = '', $width = NULL, $height = NULL, $crop = NULL, $collection = false, $fullimagelink = false, $threshold = 0, $a_class = NULL) {
	$images = getImageStatistic($number, $option, $albumfolder, $collection, $threshold);
	if (is_null($crop) && is_null($width) && is_null($height)) {
		$crop = 2;
	} else {
		if (is_null($width))
			$width = 85;
		if (is_null($height))
			$height = 85;
		if (is_null($crop)) {
			$crop = 1;
		} else {
			$crop = (int) $crop && true;
		}
	}

	echo "\n<div id=\"$option\">\n";
	echo "<ul>";
	foreach ($images as $image) {
		if ($fullimagelink) {
			$aa_class = ' class="' . $a_class . '"';
			$imagelink = $image->getFullImageURL();
		} else {
			$aa_class = NULL;
			$imagelink = $image->getLink();
		}
		echo "<li><a href=\"" . html_encode(pathurlencode($imagelink)) . "\"" . $aa_class . " title=\"" . html_encode($image->getTitle()) . "\">\n";
		switch ($crop) {
			case 0:
				echo "<img src=\"" . html_encode(pathurlencode($image->getCustomImage($width, NULL, NULL, NULL, NULL, NULL, NULL, TRUE))) . "\" alt=\"" . html_encode($image->getTitle()) . "\" /></a>\n";
				break;
			case 1:
				echo "<img src=\"" . html_encode(pathurlencode($image->getCustomImage(NULL, $width, $height, $width, $height, NULL, NULL, TRUE))) . "\" alt=\"" . html_encode($image->getTitle()) . "\" width=\"" . $width . "\" height=\"" . $height . "\" /></a>\n";
				break;
			case 2:
				echo "<img src=\"" . html_encode(pathurlencode($image->getThumb())) . "\" alt=\"" . html_encode($image->getTitle()) . "\" /></a>\n<br />";
				break;
		}
		if ($showtitle) {
			echo "<a href=\"" . html_encode(pathurlencode($image->getLink())) . "\" title=\"" . html_encode($image->getTitle()) . "\">\n";
			echo $image->getTitle() . "</a>\n";
		}
		if ($showdate) {
			echo "<p>" . formattedDate(DATE_FORMAT, strtotime($image->getDateTime())) . "</p>";
		}
		if ($showstatistic === "rating" OR $showstatistic === "rating+hitcounter") {
			$votes = $image->get("total_votes");
			$value = $image->get("total_value");
			if ($votes != 0) {
				$rating = round($value / $votes, 1);
			}
			echo "<p>" . sprintf(gettext('Rating: %1$u (Votes: %2$u)'), $rating, $votes) . "</p>";
		}
		if ($showstatistic === "hitcounter" OR $showstatistic === "rating+hitcounter") {
			$hitcounter = $image->get("hitcounter");
			if (empty($hitcounter)) {
				$hitcounter = "0";
			}
			echo "<p>" . sprintf(gettext("Views: %u"), $hitcounter) . "</p>";
		}
		if ($showdesc) {
			echo html_encodeTagged(shortenContent($image->getDesc(), $desclength, ' (...)'));
		}
		echo "</li>";
	}
	echo "</ul></div>\n";
}

**Comment by Elinth** [comment] 2019-07-31 10:54
I am getting an error per image. NOTICE: "Undefined variable: album" in .../functions.php on line 205

**Comment by Elinth** [comment] 2019-07-31 13:11
This is when I changed the following (in Bold) line in functions.php:
if ($showtitle) {
				echo "<h3><a href=\"" . html_encode($image->getLink()) . "\" title=\"" . html_encode(**$image->getTitle()**) . "\">\n";
				echo $image->getTitle() . "</a></h3>\n";
			}

**Comment by sbillard** [comment] 2019-07-31 16:17
Sorry, my typo. It should be $image->getLink() to $image->album->getlink() [without the $ in front of album.]

As to the zpArdoise theme version, wherever there is an href it should be changed to this album link.

**Comment by Elinth** [comment] 2019-07-31 16:35
This is awesome!!!! Thanks so much!! Is this also possible for:  inc_print_image_thumb.php? (For favorites etc.)

**Comment by Elinth** [comment] 2019-07-31 16:47
It does go to the album, but not the specific image?

**Comment by sbillard** [comment] 2019-07-31 22:52
I thought that is what you wanted. The original code goes to the image page of the image. If you want it to be to the album page displaying the image that is a bit more complicated.

**Comment by Elinth** [comment] 2019-08-01 07:47
Thanks so much for helping me forward. Where do I put the #n? I would be so grateful if you could show me. I'm close to have this actually working..  
if ($showtitle) {
				echo "<h3><a href=\"" . html_encode($image->album->getlink()) . "\" title=\"" . html_encode($image->getTitle()) . "\">\n";
				echo $image->getTitle() . "</a></h3>\n";
			}

**Comment by sbillard** [comment] 2019-08-01 16:39
I believe this will do the trick.

<a href="" . html_encode($image->album->getlink()) .'#'.$image->getIndex(). "" title="" . html_encode($image->getTitle()) . "">\n";
echo $image->getTitle() . "

**Comment by Elinth** [comment] 2019-08-01 16:51
Thank you so much! It does go to an image, but not the right one. It goes to the one before the actual image in the gallery. Any suggestions?

**Comment by sbillard** [comment] 2019-08-01 16:55
If it always goes to the one before just add one to the number: $image->getIndex()+1

**Comment by Elinth** [comment] 2019-08-01 17:03
Sorry for the hassle..
That did not work: WARNING: "A non-numeric value encountered" in...

**Comment by sbillard** [comment] 2019-08-01 17:17
Hmmm....

Not really sure about this one. You can try  (int) $image->getIndex()+1

Bur also for testing purposes add a line: `var_dump($image->getIndex());` so we can see what is being returned.

**Comment by Elinth** [comment] 2019-08-01 17:22
(int) $image->getIndex()+1 Didn't work. 
I added the line var_dump($image->getIndex()); You can see the behavior on my site.

**Comment by sbillard** [comment] 2019-08-01 17:27
Ok, then try 
`<a href="" . html_encode($image->album->getlink()) .'#'.($image->getIndex().+1) "" title="" . html_encode($image->getTitle()) . "">\n";
echo $image->getTitle() . "`

The value returned is ok, so it must be the way PHP is evaluating the expression.

**Comment by Elinth** [comment] 2019-08-01 18:08
It works!!!!! You rock!!! 
For  inc_print_image_thumb.php, is that really hard to do?

**Comment by sbillard** [comment] 2019-08-01 18:32
I am not at my computer right now. But you should be able to find that place that emits the link and make the same changes. On Aug 1, 2019 11:08 AM, Elinth <notifications@github.com> wrote:It works!!!!! You rock!!!
For  inc_print_image_thumb.php, is that really hard to do?

**Comment by Elinth** [comment] 2019-08-01 19:35
I assume I have to change  the inc_print_image_thumb.php file?  I played around with it but loads of errors... 
Would you like to help me with this one too?

**Comment by sbillard** [comment] 2019-08-01 20:00
Change the href line to 
`<a class="thumb" href="<?php echo html_encode($image->album->getlink()).'#'.($image->getIndex()+1); ?>" title="<?php echo html_encode(getBareImageTitle()); ?>"><?php printImageThumb(getAnnotatedImageTitle()); ?></a>`

**Comment by Elinth** [comment] 2019-08-01 20:05
I actually tried that in my attempts. When I copy your code in I receive two errors. 
NOTICE: "Undefined variable: image" in /srv/disk6/279773/inc_print_image_thumb.php on line 10

**Comment by Elinth** [comment] 2019-08-01 20:08
You can see the errors on my site under favorites. Somehow I cannot select and copy 
them

**Comment by sbillard** [comment] 2019-08-01 20:09
Ok, then change $image to `$_current_image`

**Comment by Elinth** [comment] 2019-08-01 20:21
That did the trick!! It works for favorites!! Really strange though, the only thing is that the image is way off on the search. When I search on an image in search it shows a complete different image. You can see this when you search "Tromp" on my site.

**Comment by Elinth** [comment] 2019-08-01 21:06
Ah it takes the number of image of the the search results and then shows that number in the album.
When the search results are 10 images and I click on the 8th image, it shows the 8th image in the gallerific gallery from that picture, which is a different one.

**Comment by sbillard** [comment] 2019-08-01 22:02
Yes, that is what it would do. $image->getIndex() is relative to the context. if there is a search in the context it will be relative to the search.

If you want to fix that you would have to compute an index relative to the image's album.  it "might" work to save off the value of `$_current_search`, emit the link, then restore the saved value to `$_current_search`.

otherwise the code is 
`				$images = $this->album->getImages(0);
				$target = array_keys(array_filter($images, function($item) use ($filename) {
									return $item == $filename;
								}));
				$index = @$target[0];
`

where $this is the image object variable, probably `$_current_image`.

**Comment by Elinth** [comment] 2019-08-02 05:52
Where do I put what code? Do I put this in search.php? Sorry, I am not very technical in coding.

**Comment by sbillard** [comment] 2019-08-02 15:51
Yes, it would be in the loop where the link is being printed.

**Comment by Elinth** [comment] 2019-08-03 14:22
I am getting an error:
EXCEPTION (0): "syntax error, unexpected 'else' (T_ELSE), expecting end of file" in /srv/disk6/279773/www/..../inc_print_image_thumb.php on line 8

**Comment by sbillard** [comment] 2019-08-03 15:26
The complete inc_print_thumb.php script is:
`<div id="thumbs-nogal">
	<ul class="clearfix thumbs-nogal" id="no-gal-ul">
		<?php while (next_image()) { ?>
			<li class="no-gal-li">
				<?php $fullimage = getFullImageURL(); ?>
				<?php if ((getOption('use_colorbox_album')) && (!empty($fullimage))) { ?>
					<a class="thumb colorbox" href="<?php echo html_encode($fullimage); ?>" title="<?php echo html_encode(getBareImageTitle()); ?>"><?php printImageThumb(getAnnotatedImageTitle()); ?></a>
				<?php } else { ?>
					$saveSearch = $_current_search;
					$_current_search = NULL; ?> <a class="thumb" href="<?php echohtml_encode($image->album->getlink()) . '#' . ($image->getIndex() + 1); ?>" title="<?php echo html_encode(getBareImageTitle()); ?>"><?php printImageThumb(getAnnotatedImageTitle()); ?></a> <?php
					$_current_search = $saveSearch;
				}
				?>
			</li>
<?php } ?>
	</ul>
</div>`

**Comment by sbillard** [comment] 2019-08-03 15:29
I've attached the complete, edited, inc_print_image_thumb.php file
[inc_print_image_statistic.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3463988/inc_print_image_statistic.zip)

**Comment by Elinth** [comment] 2019-08-03 15:36
But the change was for inc_print_thumb.php? Is it the right file?

**Comment by sbillard** [comment] 2019-08-03 16:10
There is no inc_print_thumb.php file in my version of zpArdoiose.

**Comment by sbillard** [comment] 2019-08-03 16:13
[inc_print_image_thumb.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3464040/inc_print_image_thumb.zip)
sorry, clicked on the wrong file

**Comment by Elinth** [comment] 2019-08-03 17:03
Thank you soo much!! 
It seems my colorbox setting is in the way. Even if I disable my setting for colorbox image it shows the colorbox. How can I disable this in the code?

**Comment by sbillard** [comment] 2019-08-03 17:22
There is an option `Use Colorbox in Album page` that must be reset.

**Comment by Elinth** [comment] 2019-08-03 17:26
For the title I previously used `<p><a` href="<?php echo html_encode(getImageURL()); ?>"><?php printBareImageTitle(); ?></a>``

**Comment by Elinth** [comment] 2019-08-03 18:22
My old file. With title and without colorbox
[inc_print_image_thumb.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3464179/inc_print_image_thumb.zip)

**Comment by Elinth** [comment] 2019-08-03 18:26
My quest is to have the same, but then that it opens in gallerific.

**Comment by sbillard** [comment] 2019-08-03 20:27
[inc_print_image_thumb-edited.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3464295/inc_print_image_thumb-edited.zip)


The learning point of all this is to replace where the image link is being emitted with the code to go to the gallery. In this case: `echo html_encode(getImageURL()); ` gets changed to `echo html_encode($_current_image->album->getlink()).'#'.($image->getIndex()+1);`

The other code added is to save the value of `$_current_search`, set it to `NULL` to trick the search stuff to using the image list from the album and not from the search. Of course the `$_current_search` must be restored once the link is emitted.

**Comment by Elinth** [comment] 2019-08-03 20:57
Tha ks so much Stephen, you are so helpful!  Somehow the zip doesn't unpack though, mind zipping it again and emailing it to me? Thank you so much, I am so grateful!

**Comment by Elinth** [comment] 2019-08-03 21:03
You made my day!!! It works like a charm! Thank you sooo much!!

**Comment by Elinth** [comment] 2019-08-03 21:23
Small note: The $image had to be changed to $_current_image

**Comment by sbillard** [comment] 2019-08-03 22:27
I must have missed one, sorry :(

**Comment by Elinth** [comment] 2019-08-04 10:18
I hope you are open to one more question on this one.. Is it possible that the comments are about the selected galleriffic image instead of the album in the album.php page?

**Comment by sbillard** [comment] 2019-08-04 15:57
While it is "possible" it would be extremely difficult. The basic problem is that the only place the specific image being shown is known is in the browser on the visitor's computer. That information somehow must be passed back to the server with the comment posting. I will look to see how difficult that might be.

**Comment by sbillard** [comment] 2019-08-05 01:36
The problem as I see it is to know what image is being viewed. To learn how that works would require studying the theme code extensively. I do not have the time to do that. Perhaps you can engage the author of the theme on this item: https://github.com/vincent3569/zpArdoise

I would refrain from mentioning that you are using netPhotoGraphics, that might kill any interest he might have. If he updates his theme it is straightforward to ;ort it to netPhotoGrahics.

I shall close this ticket now. It has drifted off the original topic.

**Closed by sbillard** 2019-08-05 01:36 UTC

**Comment by Elinth** [comment] 2019-08-05 07:20
Thanks, I was initially not aware it is so difficult. I am really glad you sorted me with the changes made now though. Kill interest? Are they against NPG?

**Comment by sbillard** [comment] 2019-08-05 15:18
Yes, they are supporters of the original zenphoto gallery software.

**Comment by sbillard** [comment] 2019-08-05 16:54
Don't make contact  just yet. I think I have a solution. Not perfect, but maybe good enough.

I can make the theme place the title of the image as the first line of the comment. Of course the person making the comment could override it but it is a start.

Stay tuned.

**Comment by Elinth** [comment] 2019-08-05 17:35
That's awesome!

**Comment by sbillard** [comment] 2019-08-05 18:49
[inc_print_comment.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3468927/inc_print_comment.zip)

This is the modified script. 

There is a line in the file that fills in the comment: 
`text = $('.image-title a').html() + "\n" + $('#comment_text').val();`

The first term is the image title of the image that is showing. So your images must have titles for this to work. The term after the `"\n"` is any existing comment text, so the code will insert the title in front of any existing comment. 

You could add text by modifying this line. This is JavaScript, so the syntax is a bit different from PHP.  So for instance you might change the line as follows:
`text = 'Comment on image $('.image-title a').html() + ":\n" + $('#comment_text').val();`

**Comment by Elinth** [comment] 2019-08-05 19:44
Hi Stephen, I uploaded your file and even tried the modified line but I see no title.  Are you sure you send the right file?

**Comment by Elinth** [comment] 2019-08-05 20:00
I see your code, it must be the right file. Someho it is not showing the title

**Comment by sbillard** [comment] 2019-08-05 20:30
Ok, the problem is that my tests were using a customized comment form. I'll see if I can make the script work with the standard one. If not I will attach the custom form which you would include in your theme folders. (In fact, maybe I just attach them now so you can use them. Can be removed later if a better solution is found.)
[comment_form.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3469319/comment_form.zip)

**Comment by Elinth** [comment] 2019-08-05 20:45
Can you zip the entire file? Just the comment_form.php did not do the trick.

**Comment by Elinth** [comment] 2019-08-05 21:21
It does work, I read over your click link comment. I once disabled the toggle, but now it seems it is biting me.

**Comment by Elinth** [comment] 2019-08-05 21:28
This is awesome though!! The only thing is how I will get around this click thingy

**Comment by Elinth** [comment] 2019-08-05 21:30
Is it possible to activate this once the cursor hits the text field?

**Comment by Elinth** [comment] 2019-08-05 21:46
Or what would really be great if it is always there without activation? (It would switch title when going through the gallery thumbnails)

**Comment by sbillard** [comment] 2019-08-05 22:32
[comment_form.zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3469600/comment_form.zip)

This  is a different implementation. You need to revert the `inc_print_commeent_form` to the original zpArdoise version and replace the local comment form with this new one. 

The title will not be inserted until the comment is posted, so the visitor will not see it unless he reviews the comment after posting.

**Comment by sbillard** [comment] 2019-08-05 22:55
There is a small problem with the above comment form--it inserts "undefined" for news or pages comments. That is corrected by 
[comment_form (2).zip](https://github.com/netPhotoGraphics/netPhotoGraphics/files/3469653/comment_form.2.zip)

**Comment by Elinth** [comment] 2019-08-06 07:19
This is awesome Stephen, this is just what I needed, thank you so much!!

**Comment by Elinth** [comment] 2019-08-06 07:27
Is it possible to make the title italic? This way it distinguishes from the text.

**Comment by sbillard** [comment] 2019-08-06 15:41
Sure, you can add to the inserted text by changing the line
`text =  text + "\n" + textarea.val();`.

In this case make it 
`text = '<em>' + text + '</em>' + "\n" + textarea.val();`

or even: 
`text = '<em>comment on image: ' + text + '</em>' + "\n" + textarea.val();`

**Comment by Elinth** [comment] 2019-08-06 16:21
Thanks soo much! How can I do image: with gettext? This way it translates..

**Comment by sbillard** [comment] 2019-08-06 16:28
text = '<em><?php echo gettext('comment on image: ');?>' + text + '</em>' + "\n" + textarea.val();

But of course this works only if the translation files have the text string translated.

**Comment by Elinth** [comment] 2019-08-06 16:33
Thanks!! You absolutely rock

**Comment by Elinth** [comment] 2019-08-06 17:16
I only used Image, that works.

**Comment by Elinth** [comment] 2019-08-12 19:27
I just did the update to the latest version of NPG and this comment script stopped working because the file is overwritten. Is there anything I can do to prevent this overwrite in the future? Or do I need to manually overwrite the plugin comment_form.php each time?

**Comment by sbillard** [comment] 2019-08-12 19:40
You should include it with your custom theme. Copy the folder and script to your theme folder.

**Comment by Elinth** [comment] 2019-08-12 20:03
So I create a folder zp-extensions with the plugin folder and that would do the trick? Sorry, first time..

**Comment by sbillard** [comment] 2019-08-12 23:28
No, in your theme folder create a folder named `comment_form` and put the script in it.
