### ISSUE TITLE
Slideshow2 issues

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1033] opened 2019-09-14 19:40 UTC
After update to 2.00.02.01 I noticed that a number of my plugins were flagged as deprecated so I made some removals and switches.  Among other things I got rid of Slideshow and changed to Slideshow2 but now slideshow2 doesn't work at all.  I normally use a "tweaked" theme (just a variation of Basic) so I switched to several other themes to see if my problem had to do with improper call to the slideshow but every theme shows the same error "Invalid linking to the slideshow page" so something about the slideshow2 plugin isn't happy.  Sometimes selecting "View Slideshow" gives me one image (but no advancement of the slideshow) other times all I get is an all black screen with only a set of slideshow controls showing across the top.

How should slideshow2 be set up? What is required for slideshow2 to work and how should a correct call to it be set up on a theme?  Thanks

NK

**Comment by sbillard** [comment] 2019-09-14 22:30
I will have to investigate the errors, but in the meantime you can continue to use slideshow. It won't actually go away for a while. The deprecated plugins will be re-installed with each run of setup until the deprecation is finalized.

**Comment by sbillard** [comment] 2019-09-15 00:51
Well, slideshow2 seems broken. Probably a javascript conflict somewhere. Unfortunately, I am not sure when the issue sufraced.

So in the meantime, slideshow will become un-deprecated.

**Comment by sbillard** [comment] 2019-09-16 00:50
I have determined the issue. For slideshow2 to work at all, the jquery migration (theme) setting must not be disabled. Even then, only the colorbox selection works. The Cycle option shows the first image but then fails to advance.

This is all caused by incompatibility of the slideshow2 jquery.cycle2 javascripts with the current version of jquery. jquery.cycle2 appears not to have been updated in almost 5 years, so I have little hope that these incompatibilities will get resolved by the developer.

Given the above analysis, most likely we will deprecate slideshow2 and keep slideshow. But I may see if it is easy to fix the compatibility issues with jquery.cycle2

**Comment by nerdykit** [comment] 2019-09-16 01:54
Thanks Stephen.  I've re-installed Slideshow and it's fine.  I had assumed that the problem was that my tweaked version of Basic theme wasn't properly calling the slideshow2 so as long as the problem isn't that, then I can just continue with the old slideshow.  Unless the new slideshow2 offers a lot more features than the old one, I don't think it's worth investing much of your time on it.  I'll leave it up to you to decide to close this "issue" or keep it active.

NK

**Comment by sbillard** [comment] 2019-09-16 21:17
After some attempts to update the cycle2 scripts I have decided it is not worth the effort. slideshow2 has now been removed to the DevTools repository just in case there ever is an update to cycle2

**Closed by sbillard** 2019-09-16 21:17 UTC
Labels: bug
