### ISSUE TITLE
Dynamic Locale and redirection from logout

### ISSUE THREAD

**Issue by OldNick** [netPhotoGraphics/netPhotoGraphics#1128] opened 2020-02-11 10:14 UTC
Dynamic locale is not working as expected on my "production" (big word...) version of my site. If you try to change the language by clicking on the flag (say, to get French), it churns a bit and then remains in the same language - although the flag indicates that the active language is French. It is only by refreshing the page through the browser that you land on the language of choice.
I'm using the "url" option - the "sub-domain" option gives me a "server not found error" I tried creating a sub-domain on the server, still doesn't work - the address doesn't show /fr/... when in french.
The function to go automatically to the language according to browser configuration works, however, so 90% of cases will work without worrying.
I did notice however that the url was being written when in admin - however it was stacking them up as I was trying to get it to work - "fr/fr/en/fr/..." again I had to browser refresh to actually get the language.

I think this is something to do with overall redirection... the other one has been catastrophic - I can no longer get into my site and, after lengthy churning, I just get a white screen.
I logged out and was taken to the home page only I wasn't logged out - there were unpublished albums and the little cog in the top right - so I used that to log out again and ended up with a white screen.

I'm not sure what to do or what to look for - setup files are hidden - I've done a backup of the database, but it's likely corrupted somewhere. Nothing in the debug.log and c-panel errors page crashed...

**Comment by sbillard** [comment] 2020-02-11 20:15
I think I can reproduce the admin part of your problem. But the front-end part works for me. It does not, indeed, show the /fr/ in the address bar so I will have to look at that as well. I cannot remember if it should--probably not to avoid unnecessary redirection. Language is stored in a cookie.

The logout issue sounds like a browser caching issue. You can try clearing the browser cache. Other options to try:

If you have access to your database you can find the option named "_plugin_dynamic-locale" and set its value to zero. This will disable the language plugin.

If you can FTP to your site, you can change the setup files with the extension "xxx" back to "php" to restore the setup files.

**Comment by sbillard** [comment] 2020-02-11 21:19
It occurs to me that since the browser configuration works for most of the cases for you that your best bet would be to disable language links in the dynamic_locale options. You would only need the language links if you wish to export links that are language based.

**Comment by OldNick** [comment] 2020-02-11 21:33
The site started working again! I went to c-panel and tried to open the errors page - which churned for near on 10 mins and the came back with a whole lot of errors and "the process dumped a core file" - which turns out to be the error log (I now have no recorded errors). Once it had dumped the file, the site started working again!
From memory, the older versions did put in "/fr/" but I see my local version doesn't either, but I don't have to do a browser refresh.

I'll go back on tiptoes and try your suggestions and hope I don't break anything again! If dynamic_locale will work without producing links, that's fine - viewers have got the flags to click on if they want to switch...!

**Comment by OldNick** [comment] 2020-02-11 21:39
Turned off the link writing and it works fine now - it doesn't churn away trying to write the new links and switches language immediately.
It could be the way the hosting company set up the servers - redirecting can have a bad reputation...

**Comment by sbillard** [comment] 2020-02-12 00:23
I did find some issues with admin pages related to when we started to have rewritable links on them. Those caused the cascading of the url. (And also made it so that any time there was "npg" somewhere in a link it might think it was an admin page request.

This is fixed now and will be uploaded shortly.

**Comment by OldNick** [comment] 2020-02-12 00:27
I noticed there is a new version - think I'll wait a couple of days before updating!

But you're very good at reacting to concerns as they're raised.

**Comment by sbillard** [comment] 2020-02-12 00:43
You can try these fixes: https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/Dev_2.0%2B

**Closed** 2020-02-13 19:19 UTC
