### ISSUE TITLE
Bootstrap video's not working

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1191] opened 2020-07-22 07:59 UTC
Hi Stephen,

The videos in the theme Bootstrap are not working and give an error in mobile view and regular view. The video's embedded from youtube do work correctly.

**Comment by sbillard** [comment] 2020-07-22 15:46
Please provide details on the error you get. Perhaps a link to the working and not working ones.

**Comment by sbillard** [comment] 2020-07-22 16:12
Ok. I enabled the themeswitcher plugin and tried this image on my desktop web browser with LHBoot as the theme. It does work there, so the issue is some kind of problem with the mobile device. Perhaps a script conflict or perhaps a problem with the device not fully supporting HTML5 videos. You can try one of the video plugins to see if that gets around the issue.

By the way, you could use themeswitcher to test out your themes, it is really convenient. You can even leave it enabled if check the "private" checkbox and insure that your users do not have "theme" rights enabled. Then only you (and I) will see the selector.

**Comment by Elinth** [comment] 2020-07-22 17:06
Themeswitcher is great! Thanks for the suggestion! Tried jplayer, that does not work either. Any other thoughts?

**Comment by Elinth** [comment] 2020-07-22 17:11
It does not work on my desktop either...

**Comment by Elinth** [comment] 2020-07-22 17:42
It may have to do with fancybox? https://fancyapps.com/fancybox/3/docs/#video

**Comment by Elinth** [comment] 2020-07-22 18:08
I turned fancybox off by removing the following, then it does work. `<?php
		}


		if (($_gallery_page == 'album.php') || ($_gallery_page == 'favorites.php') || ($_gallery_page == 'news.php') || ($_gallery_page == 'pages.php') || ($_gallery_page == 'search.php')) {
			scriptLoader($_themeroot . '/js/jquery.fancybox.min.js');
			scriptLoader($_themeroot . '/js/zpB_fancybox_config.js');
			?>`

**Comment by Elinth** [comment] 2020-07-22 18:10
Is there a code that you can turn fancybox off when something is a video?

**Comment by sbillard** [comment] 2020-07-22 23:23
You can test if you are not on an image page that is a video as follows:

`if($_Gallery_page != 'image.php' || get_class($_current_image) != 'Video'){
  load the fancybox scripts
}

**Comment by sbillard** [comment] 2020-07-24 00:04
I am going to close this now as you appear to have things under control. It is really unfortunate that the full conversation on this is not recorded here on GitHub for anyone to see and learn from. I understand that sometimes you will want to send private information via e-mail. What I suggest is that you post the content of your message less the private information here and then email just the private information.

**Closed by sbillard** 2020-07-24 00:04 UTC

**Comment by Elinth** [comment] 2020-07-24 08:25
Good point. The error was never solved. I tried this on a Samsung phone, Ipad, Iphone and the error still persisted in fancybox for only MP4 video's. I deleted my browser data on all devices and that did not do the trick. The error persisted in my custom theme but also in the regular Bootstrap theme. I contacted Vincent Bourganel, the developer of the Bootstrap theme and he sent me a test link of his theme on Zenphoto. I did not get the error message in fancybox in his test site. I think it has to do with html5. Eventually I decided to turn fancybox off for mp4 videos. I therefore made the following changes in the inc_print_image_thumb.php file

Under
//Video file,
I changed the code to `<a class="thumb" href="<?php echo html_encode(getImageURL()); ?>" title="<?php echo html_encode(getBareImageTitle()); ?>">` 
This works for me. The embeds are still working via fancybox and mp4s go through the normal image.php route.
Still strange that this error pops up.

**Comment by sbillard** [comment] 2020-07-25 00:15
There is one other possibility that I have thought of. Zenphoto is still on the obsolete jQuery version. Maybe there is a problem with fancyBox and jQuery 3. The theme is using javascript to show the video. Your change takes the javascript out of the picture [sic]. 

Some javascripts are not compatible with jQuery3. For instance, the jquery.mpbile. There are options in the debug plugin to debut or suppress migration to jQuery3. 

But there still is the issue that I could visit your site and things did work for me. Maybe you can setup a special version of your mobile theme with the old code that I could try just to be sure that I am seeing what you are seeing.

**Comment by Elinth** [comment] 2020-07-25 08:48
I put the change back on my live mobile theme LHboot so you can test with jquery. The error in fancybox is only when clicking on the thumbnail.

**Comment by Elinth** [comment] 2020-07-25 09:06
I installed Chrome on my iphone and that gives the same error.

**Comment by sbillard** [comment] 2020-07-25 16:22
I don't think the change is in. The video still works for me. Maybe make a copy of your LHboot them, say LHboot-test and leave the failing code there. Let me know when the new theme is there.

**Comment by Elinth** [comment] 2020-07-26 14:41
I put a test theme up, "LH Boottest Stephen". Its not going to do any difference, as you do not see the error and it works for you. I still have the mp4 error, also on the desktop.

**Comment by sbillard** [comment] 2020-07-26 23:13
Ok, with this theme and with the standard bootstrap I see the error. I suppose it is coming from fancybox, but as there is no information presented we don't know for sure. I tried the jQuery migration settings and it still fails. I did look for javascript errors and there were none, so it is failing in its internal code. I think therefore that your code change is the best solution.
