### ISSUE TITLE
Enable Challenge phrase keeps being activated after update

### ISSUE THREAD

**Issue by Elinth** [netPhotoGraphics/netPhotoGraphics#1263] opened 2020-11-19 11:40 UTC
Hi Stephen, after an update the "Enable Challenge phrase" function keeps being activated. I have it without a tick in the box and after the update the box is ticked.

**Comment by sbillard** [comment] 2020-11-19 17:16
I cannot reproduce this failure.

**Comment by Elinth** [comment] 2020-11-19 18:30
Ok, I'll keep an eye on it next update. See if it changes again.

**Comment by sbillard** [comment] 2020-11-19 18:41
Is the option set after the apply the un-check or is it set sometime later? If doing the apply does not make it reset there may be some problem with your options table. There is no code that would be making it set except for during setup if the option was not present in the database.

**Comment by Elinth** [comment] 2020-11-19 18:47
Not reallly sure when this happened, I am sure I haven't changed it as I have not been in that options page for quite a while. (Actually I wrote you back then if the challenge phrase could be disabled.)  I set the option back then unchecked. Somehow it changed back to being set. I happened to click on the link in the password page and noticed it. Thus my assumption that it changed during a setup sometime.

**Comment by Elinth** [comment] 2020-11-19 18:57
I just did the update to 2.00.08.04 (Production). It changed again to being checked.

**Comment by Elinth** [comment] 2020-11-19 18:58
You can run the update on my site for the latest dev release to see the behavior if necessary.

**Comment by sbillard** [comment] 2020-11-19 23:07
fixed in the DEV release

**Comment by Elinth** [comment] 2020-11-20 21:07
Thanks!

**Closed** 2020-11-23 23:32 UTC
