### ISSUE TITLE
Error: EXCEPTION (0): "Undefined constant "ALBUM_RIGHTS""

### ISSUE THREAD

**Issue by Ipstenu** [netPhotoGraphics/netPhotoGraphics#1366] opened 2021-11-11 06:36 UTC
Debug log keeps popping up with these:

```
{31181:Thu, 11 Nov 2021 06:33:23 GMT} netPhotoGraphics v2.00.13.04
EXCEPTION (0): "Undefined constant "ALBUM_RIGHTS"" in /gallery/npgCore/i.php on line 87
URI:/gallery/npgCore/i.php?a=pub/filmfest/20140330-amdocsff&i=10155764_649406975125211_5850942742010849950_n.jpg&w=580&h=386&cw=0&ch=0&q=90&wmk=!&limit=30&check=3981495598412278f2feeaeb82b07fc3440d5072&cached=182443998
IP `114.119.134.159`
npgExceptionHandler called from unknown
```

I haven't figured out anything from the IP address :/ ~Is it possible this is happening from bots/scrapers? I get a lot of those~

Edited: Nope, my own IP showed up.

I changed that line to this:

`if ($_loggedin & (defined('ALBUM_RIGHTS') && ALBUM_RIGHTS) {`

which at least shuts up the error.

**Comment by sbillard** [comment] 2021-11-11 17:45
The correct cfix would be to add `require_once(__DIR__ . '/functions.php');` just before the if statement.

But it would be interesting to know why this happens. It is presumably a cached URL since among other things the query parameter "check' was changed to "ipcheck". Maybe something in one of the "page" or "news" items?

**Comment by Ipstenu** [comment] 2021-11-11 21:35
Ah, thanks.

It seems to stem from Image Processor security being active (reverted my edits and unchecked that option, solved, though I'm not a fan of not having that mitigation - people are jerks). I wouldn't be shocked that some idiots are direct linking to things, but once I started seeing my **own** IP pop up, I got a little more confused. I wasn't trying to hit the images directly, just visited my own site.

I don't use the news (or pages) features, however I do use CloudFlare caching. My theme is custom, and it's super basic. I don't think I'm doing anything weird.

Active plugins:

* cacheManager
* lazyLoader
* noCaptcha
* oembed v0.0.3
* print_album_menu 
* security-logger 
* seo_basic

**Comment by sbillard** [comment] 2021-11-11 22:50
Yes, the check is made only if the image processor anti-flooding option is set. But more to the point, the URL that triggered the problem is an "old style" URL. This means that the URL has been captured somewhere. Generally the first time an image of a particular size, etc. is referenced the software generates an image processor URI (the i.php link.) The next time the page is regenerated the image should exist in the cache and the URL should go directly to the cached image.

If CloudFlare caches the page on the first reference (which presumably it will) then each time the page is served from the cache it will have to process the image processor URI. That is really not an ideal situation, specially if the duration of the cache is long. I don't have a good solution other than to suggest that when you add images you flush the CloudFlare cache after you have viewed all the pages that contain some instance of the image.

The above fix will prevent the error, but not the unnecessary reprocessing of the image processor URI. The good news is that the cache image does not get regenerated. i.php notices that the cached image exists and serves it up rather than regenerating it.

**Comment by sbillard** [comment] 2021-11-12 20:34
fixed in https://github.com/netPhotoGraphics/netPhotoGraphics/commit/80673df978f9134c47e0c5a5b8c042a23e32d814

**Closed by sbillard** 2021-11-12 20:34 UTC
