### ISSUE TITLE
Notification to upgrade to a lower version

### ISSUE THREAD

**Issue by Mates-K1** [netPhotoGraphics/netPhotoGraphics#1576] opened 2024-05-28 12:19 UTC
One picture is worth many words.
![Screenshot 2024-05-28 at 10-36-01 Admin Overview](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/76195b45-d5db-4fb1-9c56-f4a754f71f02)

It has been happening for the last few versions.

Usually I update either via the Update button or via the release file (extract.php).

**Comment by sbillard** [comment] 2024-05-28 16:04
This is presumably caused by the software not being able to fetch the github browser download URL.
I can think of a couple of possible causes for this.

1. Something is wrong with the option `getUpdates_lastCheck`. This is not likely, but you can remove the option from your database and see if it makes a difference. You might also remove the option `getUpdates_latest`.

2. There is some kind of error happening on fetching this URL from GitHub. One would suppose that there should have been an error logged if that were the case. On my local test sites I get SSL Certificate errors because some software somewhere does not like my self-signed certificates. If that is the problem you can disable the SSL requirement by adding the line

`$conf['GitHub_SSL_OPT'] = [CURLOPT_SSL_VERIFYPEER => 0];`

To your npg.cfg.php file towards the end of the file.
Also try enabling the `debug` plugin and clicking the "Check for updates" button.

3. The Milo\Github\Api software is not loading correctly. Again, I would expect an error message if this is happening.

The most likely cause is #3. If I modify the code to not store the URL I can reproduce your screen.

**Comment by Mates-K1** [comment] 2024-05-28 21:16
Well, after removing two options from table, reinstalling latest build from one-file setup file, `getUpdates_lastCheck` was restored and the update button has disappeared.

**Comment by sbillard** [comment] 2024-05-28 22:13
Was `getUpdates_latest` also restored? It should point to the current version. You won't get the button when the "latest" is the same as the version you are running. It will be interesting to see if this comes back when there is a new release. I think we will leave the ticket open for now.

**Comment by Mates-K1** [comment] 2024-05-29 18:18
No, `getUpdates_latest` has not been restored.

![Screenshot 2024-05-29 at 20-16-17 myadmin aerohosting cz _ mysql01 _ 2569_npg1 _ _hlavnioptions phpMyAdmin 5 1 1](https://github.com/netPhotoGraphics/netPhotoGraphics/assets/7648991/8bcb3204-4b91-4989-b2c1-26d61b337fd1)

**Comment by sbillard** [comment] 2024-05-29 23:00
So not getting the `getUpdates_latest` set can happen only if the result of the github query returns missing the assets

admin.php line 330 `$assets = $fullRepoData->assets;`

If `$assets` is empty or if there were some error in the surrounding code the option would not get stored. The same code is used to fetch the latest development build (`getDEVUJpdates_latest`) That should point to `[setup-GIT-2.01.00.11.01.zip](https://github.com/sbillard/netPhotoGraphics-DEV/releases/download/Dev_2.1%2B/setup-GIT-2.01.00.11.01.zip)` and a button to download that release should show up on the admin home page.

You could add some code to the update check to see what specifically is happening. Put a debugLog('getUpdates_latest option was set) message just after the `setOption('getUpdates_latest', $item->browser_download_url);` to see if we got into that code. If not, there must be an error, but the code should have trapped the error and logged a message about the repository not being available.

**Comment by sbillard** [comment] 2024-06-12 20:19
I am going to close this now. The 2.01.00.13 release should insure that there is an error logged when the github request for the latest version fails. Also on failure the "current release" value will be invalidated so there should be no occasion where an older release is offered.

**Closed by sbillard** 2024-06-12 20:19 UTC
