### ISSUE TITLE
EXCEPTION (8192): str_replace()

### ISSUE THREAD

**Issue by nerdykit** [netPhotoGraphics/netPhotoGraphics#1513] opened 2023-07-16 01:09 UTC
I'm getting a lot of these in the debug log file after the latest update

{21467:Sun, 16 Jul 2023 00:48:56 GMT}
EXCEPTION (8192): "str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated" in /mnt/**private path removed**/npgCore/functions.php on line 2969
URI:/gallery/npgCore/i.php?a=travel/costa-rica-2023/tortuguero&i=CRTG-001-IMG_0462-rw.jpg&w=866&h=650&cw=0&ch=0&q=95&wmk=!&ipcheck=184517bf84ae0ab6550626a5dad9b5e09b7180d8&cached=160765352
IP `**IP removed.**`
str_replace called from npgFunctions::unTagURLs (functions.php [2969])
from Image->getCredit (class-image.php [957])
from imageProcessing::cache (lib-image.php [476])
from i.php [187]

**Comment by sbillard** [comment] 2023-07-16 16:29
These are caused by PHP 8.x deprecations. Unfortunately there is no reasonable means to find the occurrences other than running into them while executing the code. 

This one can be fixed by changing line 2957 in functions.php to 
`if ($text && $_tagURLs_tags && $_tagURLs_values) {`

Please report any of these you see.

**Comment by nerdykit** [comment] 2023-07-16 17:08
I think that's got it.  I was adding a batch of new images and then viewing them so I'm not sure whether that particular function was called by the uploading of new images or the viewing action.  I'm not seeing any new debug entries after the change to line 2957.

**Comment by sbillard** [comment] 2023-07-16 22:37
It was being called as part of caching of new images. $_tagURLs_tags and $_tagURLs_values had not yet been defined. Actual fix is to move the definition from initialize-general to initialize-basic so that it is there when i.php runs to cache an image.

**Closed** 2023-07-16 23:16 UTC

**Comment by nerdykit** [comment] 2023-07-17 17:39
Just created a test album and uploaded (using modified function as above).  Did not see a new recurrence of this str_replace exception in the Debug log.  Looks as if this problem is definitely resolved.

**Comment by sbillard** [comment] 2023-07-17 17:45
Thanks for the confirmation. There will probably be more of these deprecation issues. If so please post issues for them.
